// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urcqmvbhokiwotgtsbin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyY3FtdmJob2tpd290Z3RzYmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDA1NzcsImV4cCI6MjA3MDc3NjU3N30.MrxN_BriO0Q53m2Q0SDaTPetZXjWGskd4rQ-nJJSYVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});